services:
  - type: web
    name: retroai-backend
    env: node
    buildCommand: ""
    startCommand: node server.js
    repo: https://github.com/tukuexe/retroai-backend
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
        
